/* Generated by @voxgig/sdkgen. Do not edit. */
'use strict'

const { describe, it, before } = require('node:test')
const assert = require('node:assert')

const Seneca = require('seneca')

const BrontieProvider = require('../dist/brontie-provider')
const BrontieProviderDoc = require('../dist/BrontieProvider-doc')

const SenecaMsgTest = require('seneca-msg-test')
const { Maintain } = require('@seneca/maintain')

const { SEED } = require('./seed')

const BasicMessages = require('../dist-test/basic.messages')


describe('brontie-provider', () => {

  it('happy', async () => {
    assert.notEqual(BrontieProvider, undefined)
    assert.notEqual(BrontieProviderDoc, undefined)

    const seneca = await makeSeneca()

    assert.partialDeepStrictEqual(
      await seneca.post('sys:provider,provider:brontie,get:info'),
      {
        ok: true,
        name: 'brontie',
      },
    )
  })


  it('messages', async () => {
    const seneca = await makeSeneca()
    await SenecaMsgTest(seneca, BasicMessages)()
  })


  it('sdk-export', async () => {
    const seneca = await makeSeneca()
    const sdk = seneca.export('BrontieProvider/sdk')()

    assert.equal(typeof sdk.Balance, 'function')
    assert.equal(typeof sdk.Voucher, 'function')
  })


  it('balance-load', async () => {
    const seneca = await makeSeneca()
    const found = await seneca
      .entity('provider/brontie/balance')
      .load$('balance0')

    assert.equal(found.id, 'balance0')
    assert.equal(
      found.canon$({ string: true }),
      'provider/brontie/balance',
    )
  })


  it('voucher-action-unknown-save', async () => {
    const seneca = await makeSeneca()

    await assert.rejects(
      () => seneca.entity('provider/brontie/voucher')
        .make$({ id: 'voucher0' })
        .directive$({ action$: 'no_such_action' })
        .save$(),
      /action\$ "no_such_action" is not an action/,
    )
  })


  it('maintain', async () => {
    const exclude = []

    // check_default proves the default branch is main by looking for
    // [branch "main"] in .git/config. Only a branch checkout records that
    // section: a pull_request build checks out the merge ref, and the
    // publish build checks out a tag as a detached HEAD. Neither says
    // anything about what the default branch is, so skip rather than fail.
    if ('pull_request' === process.env.GITHUB_EVENT_NAME ||
        'tag' === process.env.GITHUB_REF_TYPE) {
      exclude.push('check_default')
    }

    // url_pkgjson locates package.json by comparing process.cwd() + '/package.json'
    // against a path found with Filehound. On Windows those are the same file
    // spelt with different separators, so the url is never read.
    if ('win32' === process.platform) {
      exclude.push('url_pkgjson')
    }

    await Maintain({ exclude })
  })

})


// Default to the SDK's offline mock transport, seeded from ./seed.
async function makeSeneca(pluginopts) {
  pluginopts = pluginopts || { test: true, testopts: SEED }

  const seneca = Seneca({ legacy: false })
    .test()
    .use('promisify')
    .use('entity')
    .use('env', {
      // Declared so the provider convention is exercised, and defaulted so
      // the suite runs with nothing configured.
      var: {
        $BRONTIE_APIKEY: '',
      },
    })
    .use('provider', {
      provider: {
        brontie: {
          keys: {
            apikey: { value: '$BRONTIE_APIKEY' },
          },
        },
      },
    })
    .use(BrontieProvider, pluginopts)

  return seneca.ready()
}
