/* Generated by @voxgig/sdkgen. Do not edit. */
'use strict'

// Seed data for the SDK's offline mock transport, so the entity tests
// exercise real code paths without a server.
const SEED = {
  entity: {
    balance: {
      balance0: {"alertAt":100,"alertPercent":100,"balance":100,"currency":"currency0","id":"balance0"},
      balance1: {"alertAt":200,"alertPercent":200,"balance":200,"currency":"currency1","id":"balance1"},
    },
    voucher: {
      voucher0: {"idempotencyKey":"idempotencyKey0","product":"product0","voucherToken":"voucher0"},
      voucher1: {"idempotencyKey":"idempotencyKey1","product":"product1","voucherToken":"voucher1"},
    },
  },
}

module.exports = { SEED }
