# GENERATED by @voxgig/sdkgen. Do not edit.

.PHONY: all build test clean reset sdk-src sdk-clean regen

all: build test

build:
	npm run build

test:
	npm test

clean:
	rm -rf dist dist-test .tsbuildinfo

reset:
	npm run reset


# ---------------------------------------------------------------------------
# THIS REPOSITORY IS GENERATED, BY ITS OWN BUILDER IN .sdk/.
#
# The builder generates this package and nothing else. Its API definition
# and guide are the SDK's: everything below fetches the SDK named in
# sdk-pin.json, and `make regen` copies them from it before generating, so
# the package is built from the same model as the SDK version it depends on.
#
# NOT a git submodule, deliberately. A submodule pins a commit in git's own
# plumbing, where a stale one is invisible in a normal diff and updating it is
# a second repository operation. sdk-pin.json is an ordinary committed file,
# regenerated from the model with everything else, so it moves with the SDK
# version it belongs to and shows up in review.
# ---------------------------------------------------------------------------

SDK_PIN := sdk-pin.json
SDK_REPO := $(shell node -p "require('./$(SDK_PIN)').repo" 2>/dev/null)
SDK_TAG := $(shell node -p "require('./$(SDK_PIN)').tag" 2>/dev/null)
SDK_DIR := $(shell node -p "require('./$(SDK_PIN)').dir" 2>/dev/null)

# Point at a checkout you already have instead of fetching one:
#   make sdk-src SDK_SRC_FROM=../path/to/sdk
SDK_SRC_FROM ?=

# Fetch (or update) the SDK source at the pinned tag.
#
# A TAG, not a branch: the point is the exact revision this repository was
# generated from, so that regenerating reproduces what is committed here
# rather than whatever main happens to say today.
sdk-src:
	@set -e; \
	test -n "$(SDK_REPO)" || { echo "sdk-src: no repo in $(SDK_PIN)"; exit 1; }; \
	test -n "$(SDK_TAG)" || { echo "sdk-src: no tag in $(SDK_PIN)"; exit 1; }; \
	if [ -n "$(SDK_SRC_FROM)" ]; then \
	  echo "sdk-src: using $(SDK_SRC_FROM) (not fetching)"; \
	  rm -rf "$(SDK_DIR)"; mkdir -p "$$(dirname "$(SDK_DIR)")"; \
	  ln -s "$$(cd "$(SDK_SRC_FROM)" && pwd)" "$(SDK_DIR)"; \
	  exit 0; \
	fi; \
	if [ -d "$(SDK_DIR)/.git" ]; then \
	  echo "sdk-src: fetching $(SDK_TAG) in $(SDK_DIR)"; \
	  git -C "$(SDK_DIR)" fetch --depth 1 origin "refs/tags/$(SDK_TAG):refs/tags/$(SDK_TAG)" 2>/dev/null || \
	    git -C "$(SDK_DIR)" fetch origin "refs/tags/$(SDK_TAG):refs/tags/$(SDK_TAG)"; \
	  git -C "$(SDK_DIR)" checkout -q "refs/tags/$(SDK_TAG)"; \
	else \
	  echo "sdk-src: cloning $(SDK_REPO) at $(SDK_TAG) into $(SDK_DIR)"; \
	  rm -rf "$(SDK_DIR)"; mkdir -p "$$(dirname "$(SDK_DIR)")"; \
	  git clone --depth 1 --branch "$(SDK_TAG)" "$(SDK_REPO).git" "$(SDK_DIR)"; \
	fi; \
	echo "sdk-src: $(SDK_DIR) is at $(SDK_TAG)"

# Removes the fetched checkout AND the folder that held it. `rm -rf` on the
# checkout alone left an empty `.sdksrc/` behind — gitignored, so harmless,
# but it makes `sdk-clean` look like it did not finish. rmdir rather than
# another rm -rf: if anything else is in there, someone put it there, and
# removing it is not this target's business.
sdk-clean:
	rm -rf "$(SDK_DIR)"
	@rmdir "$$(dirname "$(SDK_DIR)")" 2>/dev/null || true

# Regenerate this repository with its own builder.
#
# The API definition and guide come from the SDK source first, so the builder
# generates from the SDK's model at the pinned tag, and generation checks the
# result against that source before writing. A linked checkout (SDK_SRC_FROM)
# is safe here: only this repository is written.
#
# To move to a newer SDK, set its version in .sdk/model/project.aontu and
# fetch that tag as you regenerate:
#
#   make regen SDK_TAG=v1.2.3
regen: sdk-src
	@set -e; \
	test -f .sdk/package.json || { echo "regen: no builder at .sdk/"; exit 1; }; \
	echo "regen: copying the API definition and guide from $(SDK_DIR)"; \
	cp -R "$(SDK_DIR)/.sdk/def/." .sdk/def/; \
	cp -R "$(SDK_DIR)/.sdk/model/guide/." .sdk/model/guide/; \
	echo "regen: installing the builder"; \
	cd .sdk && npm install && \
	echo "regen: generating" && \
	npm run generate
	@echo "regen: done — review the diff in this repository"
