/* Generated by @voxgig/sdkgen. Do not edit. */

const Pkg = require('../package.json')

const { BrontieSDK } = require('@voxgig-sdk/brontie-sdk')

const SdkPkg = require('@voxgig-sdk/brontie-sdk/package.json')


type BrontieProviderOptions = {
  // Options passed straight to the BrontieSDK constructor,
  // most usefully `base` to point at a server.
  sdk?: Record<string, any>

  // Run the SDK in offline test mode (in-memory mock transport).
  test?: boolean

  // Test feature options, e.g. {entity: {balance: {...}}} to
  // seed the mock with data. Only used when `test` is true.
  testopts?: Record<string, any>
}


function BrontieProvider(this: any, options: BrontieProviderOptions) {
  const seneca: any = this

  const entityBuilder = this.export('provider/entityBuilder')

  seneca.message('sys:provider,provider:brontie,get:info', get_info)

  async function get_info(this: any, _msg: any) {
    return {
      ok: true,
      name: 'brontie',
      version: Pkg.version,
      sdk: {
        name: '@voxgig-sdk/brontie-sdk',
        version: SdkPkg.version,
      },
    }
  }


  // Every SDK operation resolves to an SDK ENTITY rather than raw data (a
  // removed record included: it comes back marked deleted, still holding what
  // it held). Seneca wants plain data, which the entity hands over through
  // data().
  function plain(res: any) {
    return null == res ? res : res.data()
  }


  // Seneca query directives (sort$, limit$, ...) are for the store, not the
  // API, so they must not reach the SDK as match fields.
  function cleanq(q: any) {
    const out: any = {}
    for (const k in (q || {})) {
      if (!k.endsWith('$')) {
        out[k] = q[k]
      }
    }
    return out
  }


  // `action$` — the directive that selects a custom API action instead of
  // the plain cmd. READ BEFORE cleanq strips it, and still stripped from
  // what reaches the SDK as match fields: it is an instruction to the store,
  // like sort$ and limit$, not a value to filter on.
  //
  // THREE PLACES, because seneca-entity puts it in three places depending on
  // how the caller spelled it, and dropping any one of them silently turns a
  // named action into an ordinary call:
  //
  //   list$/load$/remove$({ action$ })         -> msg.q.action$
  //   ent.directive$({ action$ }).save$()      -> msg.action$
  //   const e = ent.make$({...}); e.action$=.. -> msg.ent.action$
  //
  // `make$({ action$ })` is NOT among them and cannot be: seneca-entity's
  // make$ copies only keys without a `$`, plus the four directives it knows
  // (id$, merge$, custom$, directive$), so an unknown trailing-`$` key is
  // dropped before any store sees it. `id$` reads like the precedent for
  // one, but it works only because make$ names it explicitly. The README
  // says so; there is nothing this plugin can check, because nothing arrives.
  function actionOf(msg: any) {
    const q = msg && msg.q
    const ent = msg && msg.ent

    return null != (q && q.action$) ? q.action$ :
      null != (msg && msg.action$) ? msg.action$ :
        null != (ent && ent.action$) ? ent.action$ :
          undefined
  }


  // The SDK argument for an ACTION on a read cmd: everything the caller sent
  // minus Seneca's own directives, with the id translated into the API's own
  // keys, plus the `$action` selector the SDK dispatches on.
  //
  // WIDER than the canonical argument on purpose. An action route has its own
  // parameters — GitHub's merge takes commit_title and merge_method, which the
  // canonical PATCH knows nothing about — so narrowing to the plain op's
  // required keys would strip the action's whole payload. The SDK still
  // validates: an action whose own point cannot be built is refused with
  // `point_action_invalid` rather than sent somewhere else.
  function actionq(q: any, action: string) {
    const out = cleanq(q)

    out.$action = action
    return out
  }


  // The SDK throws on any non-2xx. A 404 from a single-item read is an
  // ordinary "not found" answer rather than a failure, so return null and let
  // everything else propagate. SDK errors carry the HTTP status at the top
  // level, so ask them rather than digging into `result`.
  async function ornull(action: () => Promise<any>) {
    try {
      return await action()
    }
    catch (e: any) {
      if (true === e?.notFound) {
        return null
      }
      throw e
    }
  }

  // The custom actions each cmd can reach, as action -> SDK op. An action
  // is an alternative POINT of an ordinary op (`select.$action` in the API
  // model), so `save$` routes by this map rather than assuming update: an
  // action folded into `create` is reached through `save$` too.
  const ACTIONS: Record<string, Record<string, Record<string, string>>> = {
    ["balance"]: {
      load: {},
    },
    ["voucher"]: {
      save: {},
    },
  }


  // Resolve an `action$` to the SDK op that serves it, or REFUSE it.
  //
  // Never falls through to the ordinary call. An action name the entity does
  // not have is a caller mistake worth a message that names what is
  // available; performing a plain save instead is the one outcome that must
  // not happen, because it succeeds and does the wrong thing.
  // AN OWN PROPERTY, never an inherited one. `map[name]` resolves
  // `toString`, `constructor`, `valueOf` and the rest off Object's
  // prototype, and each of those is non-null — so the refusal below never
  // fired and the inherited function was handed to the SDK as an op name.
  // That is the silent drop in another hat: the caller named something the
  // entity does not have and was not told. An empty map inherits them all,
  // so a cmd with no actions was the most exposed.
  // THE CMD THAT WOULD WRITE TO THE WRONG RESOURCE.
  //
  // Some entities gather their ops from unrelated routes, and then a cmd's
  // only route addresses something that is not this record: `migration`'s
  // remove deletes a repository's migration ARCHIVE, `user`'s deletes a GPG
  // KEY, `pull`'s deletes a review COMMENT. The id the caller passed is not
  // in the request at all.
  //
  // Such a cmd is refused rather than sent. A caller asking to remove one
  // record must not have a different resource deleted instead, and a
  // successful-looking reply is the worst possible answer. Where the real
  // operation exists it is reachable by name, through `action$`.
  function misaddressed(
    entname: string, cmd: string, key: string, addresses: string[]
  ) {
    const own = Object.prototype.hasOwnProperty
    const ents: any = own.call(ACTIONS, entname) ? ACTIONS[entname] : {}
    const acts = Object.keys(own.call(ents, cmd) ? ents[cmd] : {}).sort()

    throw new Error(
      '@seneca/brontie-provider: ' + entname + ' ' + cmd +
      ': this API has no ' + cmd + ' route for one ' + entname +
      '. Its only ' + cmd + ' route addresses ' + addresses.join(', ') +
      ', not ' + key + ', so the id would be ignored and a different record ' +
      'changed. ' +
      (0 < acts.length ?
        'Name the operation with action$ instead: ' + acts.join(', ') :
        'No action$ of this cmd is available either'))
  }


  function actionop(name: string, entname: string, cmd: string) {
    const own = Object.prototype.hasOwnProperty
    const ents: any = own.call(ACTIONS, entname) ? ACTIONS[entname] : {}
    const map: any = own.call(ents, cmd) ? ents[cmd] : {}
    const op = own.call(map, name) ? map[name] : null

    if (null == op) {
      const valid = Object.keys(map).sort()
      throw new Error(
        '@seneca/brontie-provider: ' + entname + ' ' + cmd + ': action$ "' + name +
        '" is not an action of this operation. Valid: ' +
        (0 < valid.length ? valid.join(', ') : '(none)'))
    }

    return op
  }


  const entity: any = {
    balance: {
      cmd: {
        load: { action: (undefined as any) },
      },
    },

    voucher: {
      cmd: {
        save: { action: (undefined as any) },
      },
    },

  }


  entity.balance.cmd.load.action =
    async function load_balance(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'balance', 'load')
        const hit = await ornull(() => this.shared.sdk.Balance()[op$](actionq(msg.q, action$)))
        return null == hit ? null : entize(plain(hit))
      }

      const res = await ornull(() => this.shared.sdk.Balance().load({}))
      return null == res ? null : entize(plain(res))
    }


  entity.voucher.cmd.save.action =
    async function save_voucher(this: any, entize: any, msg: any) {
      const data = msg.ent.data$(false)
      const sdk = this.shared.sdk

      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'voucher', 'save')
        // The action's OWN payload is the entity's own fields — data$(false)
        // has already dropped every trailing-`$` key, `action$` included,
        // so `$action` is the only thing added here.
        data.$action = action$
        const done = await sdk.Voucher()[op$](data)
        return entize(plain(done))
      }

      const res = await sdk.Voucher().create(data)

      return entize(plain(res))
    }


  entityBuilder(this, {
    provider: {
      name: 'brontie',
    },
    entity
  })


  seneca.prepare(async function(this: any) {
    const sdkopts: any = Object.assign({}, options.sdk)

    // The provider convention carries credentials, so honour an `apikey`
    // when one is configured.
    const res = await this.post('sys:provider,get:keymap,provider:brontie')

    // ACCEPT `api` AS WELL AS `apikey`. The older provider convention
    // named this key `api` and read it with
    // `sys:provider,get:key,...,key:api`; the keymap message replaced that,
    // and the rename was silent. An application still configured as
    // `keys: { api: { value: ... } }` therefore resolved to undefined and
    // the SDK was constructed with NO credential at all — the request went
    // out unauthenticated and failed much later as a 401 or a 404 on
    // anything private, with nothing at startup to point at the cause.
    // `apikey` wins when both are set, so a config that has migrated is
    // unaffected.
    const apikey = res?.keymap?.apikey?.value ?? res?.keymap?.api?.value

    // Hand the credential to the SDK as `apikey`, NOT as an authorization
    // HEADER. The SDK's own auth stage owns that header: it reads
    // `options.apikey`, and on every path where it finds none it DELETES
    // `authorization` before the request goes out. A provider that set the
    // header itself was therefore never authenticated — the SDK stripped the
    // very thing it had just written, on every call, silently. The SDK also
    // owns the scheme prefix, which is resolved from the API definition
    // rather than assumed to be `Bearer`.
    if (null != apikey && '' !== apikey) {
      sdkopts.apikey = apikey
    }

    // AN UNRESOLVED CREDENTIAL IS SAID OUT LOUD. This API declares
    // authentication, so reaching here with nothing configured means every
    // call goes out unauthenticated. That is not always wrong — public
    // read-only endpoints work, at a much lower rate limit — so this warns
    // rather than throwing, and names both accepted key spellings so a
    // misnamed key is obvious from one line of log. Silence here is what
    // made the `api` -> `apikey` rename above cost a debugging session
    // instead of a glance.
    else {
      this.log.warn({
        fix: 'unauthenticated',
        note: 'no brontie credential resolved from the keymap ' +
          '(looked for keys.apikey then keys.api); requests will be sent ' +
          'unauthenticated and will fail on anything non-public',
      })
    }

    this.shared.sdk = options.test
      ? BrontieSDK.test(options.testopts || {}, sdkopts)
      : new BrontieSDK(sdkopts)
  })


  return {
    exports: {
      sdk: () => this.shared.sdk,
    },
  }
}


// Default options.
const defaults: BrontieProviderOptions = {
  sdk: {},
  test: false,
  testopts: {},
}

Object.assign(BrontieProvider, { defaults })

export default BrontieProvider

if ('undefined' !== typeof module) {
  module.exports = BrontieProvider
}
